version: 1.1.{build}
os: Visual Studio 2015

configuration: Release

pull_requests:
  do_not_increment_build_number: true
  
init: 
  - git config --global core.autocrlf true
  - ps: $env:GIT_HASH=$env:APPVEYOR_REPO_COMMIT.Substring(0, 10)
  
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}.0"
  assembly_file_version: "{version}.0"
  assembly_informational_version: "{version}.0 $(GIT_HASH)"

before_build:
  - ps: >-
      Get-ChildItem -Path .\ -Filter project.json -Recurse -Name |
      ForEach {
          $content = Get-Content "$_"
          $content = $content.Replace("99.99.99-dev", "$($env:APPVEYOR_BUILD_VERSION)")
          Set-Content "$_" $content -Encoding UTF8
      }
  - dotnet restore -v Minimal

build_script: 
  - dotnet pack "src\Exceptionless.RandomData" -c Release -o artifacts
  
test_script:
  - dotnet test "src\Exceptionless.RandomData.Tests"

artifacts:
  - path: artifacts\*.nupkg
    name: ReleaseArtifacts
  
deploy:
  - provider: Environment
    name: NuGet
    on:
      branch: master
  - provider: GitHub
    auth_token:
      secure: 0s81q7bweVLTFSOKxnIhan7el6bIFiN8HJ1kYJzOkeFXX7wgGSq9bs/rV53X9qpf
    draft: true
    on:
      branch: master
      appveyor_repo_tag: true
      
notifications:
  - provider: Slack
    channel: '#notifications'
    auth_token:
      secure: PigIGGo7UUDwdb0KGM/s7OfpAng/OMJx7q33jKfzudFBiXi1EBEd0DRmkbCc7CiX
