version: 1.1.{build}
os: Visual Studio 2017
clone_depth: 2
configuration: Release

pull_requests:
  do_not_increment_build_number: true
  
init: 
  - git config --global core.autocrlf input
  - ps: $env:GIT_HASH=$env:APPVEYOR_REPO_COMMIT.Substring(0, 10)
  - ps: If ("$env:APPVEYOR_REPO_TAG" -ne "true") { $env:VERSION_SUFFIX="pre" }
  - ps: 'Write-Output "Version: $($env:APPVEYOR_BUILD_VERSION)-$($env:VERSION_SUFFIX)"'
  - nuget sources add -name Foundatio -source https://ci.appveyor.com/nuget/foundatio

before_build:
  - ps: .\build\Set-BuildVersion -Version $env:APPVEYOR_BUILD_VERSION -Suffix $env:VERSION_SUFFIX
  - appveyor-retry dotnet restore -v Minimal

build_script: 
  - dotnet pack "src\Exceptionless.RandomData" -c Release -o artifacts
  
test_script:
  - dotnet build -c Release
  - dotnet pack -c Release

artifacts:
  - path: artifacts\*.nupkg
    name: ReleaseArtifacts

nuget:
  project_feed: true
  disable_publish_on_pr: true
  
deploy:
  - provider: Environment
    name: NuGet
    on:
      appveyor_repo_tag: true
  - provider: GitHub
    auth_token:
      secure: 0s81q7bweVLTFSOKxnIhan7el6bIFiN8HJ1kYJzOkeFXX7wgGSq9bs/rV53X9qpf
    draft: true
    on:
      branch: master
      appveyor_repo_tag: true
      
notifications:
  - provider: Slack
    channel: '#notifications'
    auth_token:
      secure: PigIGGo7UUDwdb0KGM/s7OfpAng/OMJx7q33jKfzudFBiXi1EBEd0DRmkbCc7CiX
