version: 1.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}.0"
  assembly_file_version: "{version}.0"
  assembly_informational_version: "{version}.0"

before_build:
  - nuget restore

configuration: Release

build:
  publish_nuget: true
  publish_nuget_symbols: true
  
deploy:
  - provider: Environment
    name: Exceptionless NuGet